### ISSUE TITLE
secret 키 외부 노출

### ISSUE THREAD

**Issue by RDDcat** [DDD-Community/KDKD-Server#91]
application.spring.datasource.url=jdbc:mysql://kdkd-db.cgbr3pjfc7a1.ap-northeast-2.rds.amazonaws.com/kdkd?serverTimezone=Asia/Seoul
application.spring.datasource.username=admin
application.spring.datasource.password=
application.jwt.secret=
application.jwt.secret_refresh=

외부에서 해당 키를 확인할수 있음

권한 없는 외부인이 테이블 조작 가능

**Comment by ChooSeoyeon** [comment]
헉 정말 감사합니다. 혹시 이거 어디서 확인하신 건지 여쭤봐도 될까요?? env에 환경변수 처리해서 올렸다 생각했는데 어디서 공개되어 있는건지 모르겠습니다 @RDDcat

**Comment by ChooSeoyeon** [comment]
혹시 도커허브에서 pull해가셔서 열어보신 걸까요??? 그렇다면 도커허브 리포를 private으로 바꿔야 할 거 같아서요

**Comment by RDDcat** [comment]
도커 허브는 모두에게 공개되어있는 곳입니다. 깃헙과 동일하게요.

cicd관련 블로그 글 삭제 or 수정하시고요.

해결방식은 여러가지 입니다.

1. yml 파일에서 도커 이미지를 추론못하게 github secret 사용 (잠재적 위험 있음)
2. 외부에서 키를 주입받아서 실행하는 방식으로 프로젝트 셋팅을 변경
3. 말씀하신 도커 private 서버를 운영

하는 방법이 있을것 같습니다.

**Comment by ChooSeoyeon** [comment]
@RDDcat 답변 감사합니다:) 

해결방식으로 말씀주신 것들에 대해 답변드리자면,

1. (+3) 현재 github secret을 사용하고 있습니다. 다만, 현재는 `docker username`만 secret처리해두었고 `dockerhub 리포지토리명`은 secret 처리를 하지 않았습니다. 이 부분은 부주의했던 거 같네요. 도커허브에 리포지토리명만 검색해도 찾을 수 있으니......  물론 리포지토리명 역시 안 올린다해도 결론적으론 public 레포면 어쨌든 검색 시 뜨기에 private으로 변경해줘야 할 거 같습니다.  (private으로 변경해줬습니다)

2. github secret 말고 docker secret을 쓰는 방식으로 가면 docker 컨테이너 내에서 마운트가 불가능하다 하네요. 이미지에 secret 내용을 포함해 올리는 게 아니고, 이미지 pull 받아가서 컨테이너 띄울 때 secret 내용을 주입해주는 방식이라서요. 말씀주신 것처럼 외부에서 주입 받아 해결하는 느낌이지요. RDDcat 님께서 저희 secret 내용을 보신 경로가 컨테이너를 통해 들어가 보신거였다면 secret을 나중에 주입하는 방식으로 바꿔 해결해주면 될 거 같습니다.  
**_pull 받은 이미지로 도커 컨테이너를 직접 띄우고 컨테이너에 접속 혹은 마운트해서 secret 내용을 보신 게 맞을까요??? 아님 다른 경로로 보신거면 그 부분을 막아야 할 거 같아 정확히 어떻게 해서 저희 secret 내용을 보신 건지 답변 해주시면 정말정말 감사할 거 같습니다....._** (<- 이 부분이 가장 궁금합니다) 혹시 이 부분은 깃에 쓰기 민감할 거 같다 판단되시면 제 이메일로라도 보내주시면 꼭 사례드리겠습니다...! choo000407@naver.com 입니다.


추가적으로 궁금한 부분들이 있는데요,

a. @RDDcat 님은, 제 `docker username`은 어떻게 아신건지 여쭤봐도 될까요? 블로그 보고 아신 건가요? 아님 이메일과 같아서 유추하신걸까여? 

b. 저는 도커허브 리포지토리를 public으로 뒀던 이유가 jar 파일을 이미지로 말아 올린 거라 설령 누군가 pull 받아간다하더라도 이미지 내부의 실제 파일 내용은 볼 수 없으리라 생각해서 였습니다. 이 부분 혹시 제가 잘못 알고 있는 걸까요? 이슈 내용 보면 파일 내용을 전부 보신 거 같은데 파일 내용을 어떻게 보신건지 궁금합니다.

> 더 덧붙이자면 저는 도커허브에서 누군가 pull 받아가서 (파일 내용은 보지 못하는 채로) 실행하려 한다면, rds 보안규칙에 걸려 실행 못하게 하려 했습니다. 현재는 보안규칙을 잠시 풀어둬서 접속 가능하셨던 거 같습니다. 이 부분은 특정 ip만 접속할 수 있게 보안규칙 걸어두면 해결 가능한 부분이라 생각했습니다.

c. cicd 관련 블로그 글에 올려둔 내용들 중 공개되면 안되는 내용들은 전부 숫자를 임의로 조작해서 올리거나 가려서 올려뒀었습니다. 혹시 어떤 부분 때문에 블로그 글 수정 말씀하시는 건지 알려주실 수 있나요? 혹시 제가 깜빡하고 올린 게 있고 그걸 보신건가 해서요. 최대한 주의해서 올렸었고 제가 쭉 다시 봐봤을 땐 공개하면 안되는 내용들이 올라간 건 안 보이는데 어느 부분 말씀하시는 건지 궁금합니다.

**Comment by RDDcat** [comment]
cicd 블로그 글에 본인의 민감한 내용을 가리라는 내용이 아니라 보안상 취약점이 있는 코드를 게시하지 말아달라고 부탁드리는 겁니다.

많은 블로그 글들이 현재 주니어 개발자들에 의해 무지성 복재 재배포 되고있고 생각없이 따라하는 프로젝트가 굉장히 많이 보입니다.

특히 @ChooSeoyeon 님처럼 신뢰감있는 스피커의 글이 잘못됐을 경우 문제가 심합니다. 다른 블로그글이 참조링크로 걸어두며 따라합니다. 

@ChooSeoyeon 님의 프로젝트에 접근하게 된 경위가 궁금하신것 같으신데요. CICD 에 대한 정보를 찾아보고 "다른" 블로그에서 동일한 방식을 확인해서 사용하고 있다가, 일주일쯤의 시간이 지난뒤 문득 해당방식이 도커허브에서는 sercret이 공개된 형식이겠다 싶어서 제 프로젝트를 확인해보다가 취약점을 알게되었습니다. 

생각없이 따라한 저도 문제지만 다른 프로젝트는 어떻게 하길래 유출이 안되지 의문이 들어 touch방식을 이용한 sercret.properties 복사방식을 게시한 구글에 있는 모든 블로그글을 대강 전수조사했습니다. 블로그에서 깃헙계정이 추론이 되는 게시글 우선으로 확인하였으며 도커 이미지와 도커 계정의 경우에는 깃헙에 제일 최신으로 커밋하며 기여하는 프로젝트를 확인하여 프로젝트 명을 넣는방식으로 찾아냈습니다. 도커 이미지 이름과 프로젝트 이름이 많이 다른경우는 흔하지 않습니다. 계정이 다른경우는 많이 있던 것과 별개로요. 
(본인의 경우에는 kdkd 였습니다.)

ps, 이미지를 마운트해서 내용을 열어본 방식이 맞습니다. 사례는 궁금하긴한데 비밀이 없으니 아쉽네요 ㅋㅋ
ps2, b에 덧붙인 내용은 제 생각도 동일합니다. 단지 개인 혹은 동아리같이 작은 프로젝트에서는 조금 비효율적인 면은 있는것 같네요.

**Comment by ChooSeoyeon** [comment]
아아 맞습니다. secret 키가 올라가 있어 말씀해주시는 건가 해서 오해했네요.  
github secret말고 docker secret 사용해서 처리해야 한다고 블로그 글 수정하겠습니다. 
저도 최대한 올바른 내용들만 기재하려 노력했는데 당시에 docker 보안적인 부분을 놓쳤던 거 같네요.
저도 완전히 놓치고 지나갔던 부분인데 짚어주셔서 정말 정말 감사합니다. 
개인적으로 간단한 커피 기프티콘이라도 드리고 싶은데 이메일 보내주세요:) @RDDcat 

ps. 블로그 글은 일단 dockerhub 리포지토리를 private으로 생성하라고 관련 글들에 전부 하이라이팅해 써뒀습니다.
docker secret 관련 내용은 저도 더 확실히 제 프로젝트에 적용해보고 보안상 안전한 게 확인되면 따로 작성하면 좋을 거 같네요.

**Comment by RDDcat** [comment]
고생하셨습니다  :)

이슈 닫도록하겠습니다.
